import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-black my-[4rem] sm:my-[6rem] px-4 lg:px-6 py-4">
      {children}
    </div>
  );
}
